import { useMemo, useState } from 'react';
import { ArrowDown, ArrowUpRight, FlaskConical, Menu, RotateCcw, Sparkles, Waves, X } from 'lucide-react';
import { applications, sources } from './data';

const soil = Array.from({ length: 30 }, (_, i) => ({ x: 8 + ((i * 37) % 84), y: 10 + ((i * 53) % 72), r: 10 + (i % 4) * 3 }));

function Button({ children, onClick, secondary = false }: { children: React.ReactNode; onClick?: () => void; secondary?: boolean }) {
  return <button className={`btn ${secondary ? 'btn-secondary' : ''}`} onClick={onClick}>{children}</button>;
}
function Section({ id, eyebrow, title, children, className = '' }: { id: string; eyebrow: string; title: React.ReactNode; children: React.ReactNode; className?: string }) {
  return <section id={id} className={`section ${className}`}><div className="section-head"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{children}</section>;
}
function LabGraphic({ stage, ambient = false }: { stage: number; ambient?: boolean }) {
  return <div className={`lab-graphic stage-${stage}`} aria-label="Conceptual soil stabilization visualization">
    <div className="soil-bed" />
    {soil.map((p, i) => <span key={i} className="particle" style={{ left: `${p.x}%`, top: `${p.y}%`, width: p.r, height: p.r }} />)}
    {(stage >= 1 || ambient) && Array.from({ length: 11 }, (_, i) => <span key={`b${i}`} className="bacterium" style={{ left: `${18 + ((i * 29) % 68)}%`, top: `${20 + ((i * 41) % 58)}%`, animationDelay: `${i * .14}s` }} />)}
    {stage >= 2 && Array.from({ length: 15 }, (_, i) => <span key={`c${i}`} className="crystal" style={{ left: `${13 + ((i * 31) % 74)}%`, top: `${20 + ((i * 47) % 55)}%`, animationDelay: `${i * .1}s` }} />)}
    {stage >= 3 && <div className="bridges">{Array.from({ length: 13 }, (_, i) => <i key={i} style={{ left: `${13 + ((i * 37) % 70)}%`, top: `${23 + ((i * 17) % 50)}%`, transform: `rotate(${(i * 33) % 180}deg)` }} />)}</div>}
    <div className="graphic-label">{ambient ? 'MICROBIOLOGICAL SOIL MATRIX' : stage === 0 ? 'LOOSE GRANULAR SOIL' : stage < 3 ? 'REACTIVE PRECIPITATION' : 'BONDED CALCITE NETWORK'}</div>
  </div>;
}
function App() {
  const [presentation, setPresentation] = useState(false); const [menu, setMenu] = useState(false);
  const [labStage, setLabStage] = useState(0); const [quake, setQuake] = useState(false); const [brick, setBrick] = useState(false); const [appIndex, setAppIndex] = useState(0);
  const [tonnes, setTonnes] = useState(100);
  const emissions = useMemo(() => ({ opc: tonnes * 875, bio: tonnes * 125 }), [tonnes]);
  const nav = [['SCIENCE', 'science'], ['SIMULATOR', 'simulator'], ['CARBON', 'carbon'], ['BIO-BRICK', 'bio-brick'], ['VERDICT', 'verdict']];
  const go = (id: string) => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  return <div className={presentation ? 'app presentation' : 'app'}>
    <header className="nav"><a className="brand" href="#top"><span className="brand-mark">✦</span><span>MICP <em>LAB</em></span></a><button className="mobile-menu" onClick={() => setMenu(!menu)}>{menu ? <X /> : <Menu />}</button><nav className={menu ? 'open' : ''}>{nav.map(([label, id]) => <a key={id} href={`#${id}`} onClick={() => setMenu(false)}>{label}</a>)}<button className="mode" onClick={() => setPresentation(!presentation)}>{presentation ? 'EXIT MODE' : 'PRESENTATION MODE'}</button></nav></header>
    <main id="top">
      <section className="hero"><div className="hero-copy"><span className="eyebrow">CIVIL ENGINEERING × BIOTECHNOLOGY</span><h1>Can bacteria build<br /><i>the future</i> of construction?</h1><p>Exploring Microbially Induced Calcite Precipitation as a sustainable alternative for soil stabilisation and cement-based construction.</p><div className="actions"><Button onClick={() => go('simulator')}>ENTER MICP LAB <ArrowUpRight size={16} /></Button><Button secondary onClick={() => go('science')}>EXPLORE THE SCIENCE <ArrowDown size={16} /></Button></div></div><LabGraphic ambient stage={labStage >= 3 ? 3 : 0} /><div className="hero-foot"><span>01 / 11</span><span>ENGINEERING SOIL. NATURALLY.</span></div></section>
      <Section id="science" eyebrow="01 — THE CEMENT PROBLEM" title={<>The material beneath<br /><i>the material.</i></>}><div className="problem-grid"><div><p className="lead">Ordinary Portland Cement has built the modern world — and carries a significant industrial footprint with it.</p><div className="stat-row"><div className="stat"><strong>~900</strong><span>kg CO₂ / tonne of cement</span></div><div className="stat"><strong>4–8%</strong><span>of global anthropogenic CO₂</span></div></div></div><div className="bar-compare"><div className="bar-label"><span>OPC / CARBON INTENSITY</span><b>850–900</b></div><div className="bar"><i style={{ width: '100%' }} /></div><div className="bar-label green"><span>BIO-CEMENT / RANGE</span><b>100–150</b></div><div className="bar"><i style={{ width: '18%' }} /></div><small>kg CO₂ per tonne · indicative range from project research</small></div></div></Section>
      <Section id="process" eyebrow="02 — THE BIOLOGY" title={<>How MICP turns<br /><i>biology into structure.</i></>} className="process-section"><div className="process-layout"><div className="process-list">{[['01', 'ENZYMATIC CATALYSIS', 'Urease-producing bacteria hydrolyse urea — 10¹⁴× faster than the uncatalysed reaction.'], ['02', 'CaCO₃ CEMENTATION', 'Reaction products precipitate calcite crystals that bridge and bind soil particles.'], ['03', 'IN-SITU TREATMENT', 'Bacteria are injected directly into the ground — no excavation required.']].map(([n, title, copy], i) => <button className={labStage === i + 1 ? 'process-item active' : 'process-item'} key={n} onClick={() => setLabStage(i + 1)}><span>{n}</span><div><b>{title}</b><p>{copy}</p></div><ArrowUpRight size={18} /></button>)}</div><div className="reaction-flow"><span>SOIL PARTICLES</span><ArrowDown /><span>UREASE-PRODUCING BACTERIA</span><ArrowDown /><span className="copper">UREA HYDROLYSIS</span><ArrowDown /><span className="green-text">CaCO₃ PRECIPITATION</span><ArrowDown /><span>CALCITE CRYSTALS → BONDED SOIL</span></div></div></Section>
      <Section id="simulator" eyebrow="03 — INTERACTIVE MICP LAB" title={<>Engineer soil.<br /><i>Watch it bond.</i></>} className="lab-section"><div className="lab-panel"><div className="lab-top"><div><span className="eyebrow">CONCEPTUAL EDUCATIONAL VISUALIZATION</span><h3>SOIL COLUMN / LIVE REACTION</h3></div><span className="status"><i /> {labStage === 3 ? 'TREATMENT COMPLETE' : `STAGE 0${labStage + 1} / 04`}</span></div><LabGraphic stage={labStage} /><div className="lab-controls">{['INJECT BACTERIA', 'ADD REACTANTS', 'PRECIPITATE CaCO₃', 'STABILISE SOIL'].map((label, i) => <button key={label} className={labStage > i ? 'done' : ''} disabled={labStage !== i && !(labStage === 3 && i === 3)} onClick={() => setLabStage(i === 3 ? 3 : i + 1)}><span>0{i + 1}</span>{label}{labStage > i && ' ✓'}</button>)}<button className="reset" onClick={() => setLabStage(0)}><RotateCcw size={15} /> RESET</button></div>{labStage === 3 && <div className="complete"><Sparkles size={18} /><b>MICP TREATMENT COMPLETE</b><span>Calcite bridges have bonded the soil particles.</span></div>}</div></Section>
      <Section id="earthquake" eyebrow="04 — EARTHQUAKE LAB" title={<>Can stabilization reduce<br /><i>the effects of liquefaction?</i></>}><div className={quake ? 'quake-models shaking' : 'quake-models'}>{[['UNTREATED SOIL', 'Foundation settlement', 'unstable'], ['MICP-TREATED SOIL', 'Calcite-bonded matrix', 'stable']].map(([name, copy, cls]) => <div className={`quake-card ${cls}`} key={name}><div className="building"><span /><span /><span /></div><div className="foundation" /><div className="soil-lines" /><b>{name}</b><small>{copy}</small></div>)}</div><div className="center-actions"><Button onClick={() => setQuake(!quake)}>{quake ? 'RESET SIMULATION' : 'SIMULATE EARTHQUAKE'} <Waves size={16} /></Button><small>Conceptual educational visualization — not a numerical engineering model.</small></div><div className="metric-strip"><div><strong>80%</strong><span>SETTLEMENT REDUCTION</span></div><div><strong>98%</strong><span>TILTING REDUCTION</span></div><div><strong>44%</strong><span>VOLUME SAVINGS</span></div></div></Section>
      <Section id="carbon" eyebrow="05 — CARBON IMPACT CALCULATOR" title={<>A different kind of<br /><i>bottom line.</i></>}><div className="carbon-grid"><div className="input-panel"><label>PROJECT SCALE</label><div className="number-input"><input type="number" min="1" value={tonnes} onChange={e => setTonnes(Math.max(1, Number(e.target.value) || 1))} /><span>TONNES OF CEMENT</span></div><p>Midpoint assumptions: OPC 875 kg CO₂/t · bio-cement 125 kg CO₂/t.</p><span className="eyebrow">BASED ON RANGES PRESENTED IN THE PROJECT RESEARCH.</span></div><div className="carbon-results"><div className="result-row"><span>OPC / ESTIMATED</span><b>{emissions.opc.toLocaleString()} <small>kg CO₂</small></b><div className="result-bar"><i style={{ width: '100%' }} /></div></div><div className="result-row green"><span>BIO-CEMENT / ESTIMATED</span><b>{emissions.bio.toLocaleString()} <small>kg CO₂</small></b><div className="result-bar"><i style={{ width: '14.3%' }} /></div></div><div className="difference"><span>POTENTIAL DIFFERENCE</span><strong>{(emissions.opc - emissions.bio).toLocaleString()} kg CO₂</strong></div></div></div></Section>
      <Section id="applications" eyebrow="06 — APPLICATIONS" title={<>Where can MICP<br /><i>be used?</i></>}><div className="application-layout"><div className="application-orbit">{applications.map(([name], i) => <button key={name} className={appIndex === i ? 'selected' : ''} onClick={() => setAppIndex(i)}><span>0{i + 1}</span>{name}</button>)}</div><div className="application-detail"><span className="eyebrow">FIELD OF APPLICATION / 0{appIndex + 1}</span><h3>{applications[appIndex][0]}</h3><p>{applications[appIndex][1]}</p><div className="terrain"><span /><span /><span /><span /></div></div></div></Section>
      <Section id="midp" eyebrow="07 — TWO-STAGE LIQUEFACTION MITIGATION" title={<>The dual mechanism<br /><i>of MIDP.</i></>}><div className="midp-flow">{['SOIL', 'STAGE 1 / DENITRIFICATION', 'DESATURATION', 'STAGE 2 / MICP', 'CaCO₃ CEMENTATION', 'RESTORED STIFFNESS'].map((x, i) => <div key={x}><span>{String(i + 1).padStart(2, '0')}</span><b>{x}</b>{i < 5 && <ArrowDown />}</div>)}</div></Section>
      <Section id="durability" eyebrow="08 — DURABILITY" title={<>Built for the<br /><i>long cycle.</i></>}><div className="durability"><div className="chart"><div className="axis-label">RELATIVE PERFORMANCE</div><svg viewBox="0 0 640 250" role="img" aria-label="Qualitative wet-dry cycling trend"><path d="M40 28H620M40 90H620M40 152H620M40 214H620" className="gridline" /><path d="M40 35 C90 42 110 86 160 98 S235 105 285 113 S355 132 405 151 S480 166 540 188 S590 197 620 203" className="line copper-line" /><path d="M40 35 C90 42 110 74 160 79 S235 83 285 86 S355 90 405 93 S480 97 540 102 S590 105 620 108" className="line green-line" /><path d="M40 35 C90 46 110 92 160 116 S235 128 285 139 S355 154 405 169 S480 182 540 198 S590 207 620 218" className="line cream-line" /></svg><div className="x-axis"><span>1</span><span>10</span><span>30</span><span>50 WET–DRY CYCLES</span></div></div><div className="chart-legend"><span><i className="dot copper" />Plain MICP</span><span><i className="dot green" />Fiber-Reinforced MICP</span><span><i className="dot cream" />OPC System</span><p>Stage 1: cycles 1–10 show initial calcite dislodgement. Stage 2: cycles 30–50 show a second deterioration phase; fiber reinforcement significantly arrests the decline.</p></div></div><div className="metric-strip service"><div><strong>70–85%</strong><span>STRENGTH RETAINED / 50 CYCLES</span></div><div><strong>40–60%</strong><span>OPC DEGRADATION BENCHMARK</span></div><div><strong>+15–25</strong><span>YEARS DESIGN LIFE</span></div></div></Section>
      <Section id="bio-brick" eyebrow="09 — ENGINEERED LIVING MATERIAL" title={<>Self-healing<br /><i>bio-brick.</i></>}><div className="brick-layout"><div className={`brick ${brick ? 'cracked' : ''}`} onClick={() => setBrick(true)}><div className="brick-face" /><div className="brick-crack" /></div><div className="brick-copy"><span className="eyebrow">AUTONOMOUS CRACK SEALING</span><h3>{brick ? 'CRACK SEALED' : 'A brick with a second life.'}</h3><p>{brick ? 'Bacterial spores reactivate → CaCO₃ deposition → crack sealed.' : 'Embedded bacterial spores reactivate on crack exposure, autonomously depositing CaCO₃ to seal damage.'}</p><Button secondary onClick={() => setBrick(!brick)}>{brick ? 'RESET BRICK' : 'CREATE CRACK'}</Button><div className="stat-row"><div className="stat"><strong>15–25</strong><span>MPa compressive strength</span></div><div className="stat"><strong>40–60%</strong><span>lower embodied carbon</span></div></div></div></div></Section>
      <Section id="lifecycle" eyebrow="10 — COST & LIFECYCLE" title={<>The long view<br /><i>of a living material.</i></>}><div className="timeline">{[['YEAR 0', '10–15% higher upfront cost', 'INITIAL PREMIUM'], ['YEARS 1–8', '30–50% lower maintenance', 'SAVINGS ACCUMULATE'], ['YEARS 8–12', 'Potential cost recovery', 'PAYBACK WINDOW'], ['LONGER DESIGN LIFE', '+15–25 years', 'LIFECYCLE VALUE']].map(([year, title, label], i) => <div key={year} className="timeline-item"><span>{year}</span><div className="timeline-dot">0{i + 1}</div><b>{title}</b><small>{label}</small></div>)}</div><div className="carbon-callout"><strong>650–750</strong><span>kg CO₂/m³ avoided across project lifecycle</span></div></Section>
      <Section id="verdict" eyebrow="11 — FINAL VERDICT" title={<>The future may not be<br /><i>just concrete.</i></>} className="verdict"><p className="verdict-question">What if we could engineer soil with biology?</p><div className="final-metrics"><span>LOWER CARBON</span><span>BETTER SOIL STABILITY</span><span>LONGER SERVICE LIFE</span><span>SELF-HEALING MATERIAL POTENTIAL</span></div><Button onClick={() => go('simulator')}>RUN THE MICP LAB AGAIN <RotateCcw size={16} /></Button></Section>
    </main><footer><span>MICP LAB / ENGINEERING SOIL. NATURALLY.</span><span>Sources & Notes — {sources}</span></footer>
  </div>;
}
export default App;
